# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Machine Learning and Data Science Portfolio
email: Blake.Samaha16@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My name is Blake Samaha and this is a portfolio containing some passion projects of mine.
  Enjoy peruising my work and if you wish to interact with me you can find my links to all of my social
  media accounts on this webpage!
twitter_username: Mean_Agression
github_username: bsamaha
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: benbalter/retlab #mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-theme-time-machine
  - jekyll-jupyter-notebook

author:
  name   : "Blake Samaha"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Data Driven Decision Making"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/blakesamaha/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/Mean_Agression"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bsamaha"
    - label: "Medium Blog"
      icon: "fab fa-medium"
      url: "https://medium.com/@blake.samaha16"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/Mean_Agression"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/samaha"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/blakesamaha/"
    - label: "Medium Blog"
      icon: "fab fa-medium"
      url: "https://medium.com/@blake.samaha16"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
